### ISSUE TITLE
Lack of SSR compatibility

### ISSUE THREAD

**Issue by PlkMarudny** [KTibow/m3-svelte#119]
Looks like `CalendarPicker` for example, is not SSR compatible.

**Comment by KTibow** [comment]
DatePickerDocked couldn't work without JS. You can't change the value of an input or go across months without running code on the client. That's why DateField falls back to the built in picker.
If you have a different component you want to directly use, let me know. Otherwise I'll close this issue in a few days.

**Comment by KTibow** [comment]
@PlkMarudny follow up?
